apiVersion: v1
kind: Service
metadata:
  name: {{ template "weechat.fullname" . }}
  labels:
    app: {{ template "weechat.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: {{ template "weechat.fullname" . }}
    port: 80
    targetPort: weechat
  selector:
    app: {{ template "weechat.fullname" . }}
