dependencies:
  - name: glowingBear
    version: 0.1.0
    repository: file://charts/glowing_bear
    condition: glowingBear.enabled
  - name: weechat
    version: 0.1.0
    repository: file://charts/weechat
